### ISSUE TITLE
app requests /organizations after clicking logout. #7

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#31]

**Comment by davewood** [comment]
what I think is going on:

1) click logout
2) app sends req to /logout, on success clear session
3) clicking logout sends user to /login where the session is checked, since the request from (2)
  hasn't returned yet the session is still active and /organization_list is visited


the confusing part is that the home.js controller is visited twice if you click logout and i have yet to figure out why.

**Comment by davewood** [comment]
fixed: https://github.com/certat/customer-portal/commit/6f81a1f4fb97adf3cfb3d89926dbcca88a469bff
