### ISSUE TITLE
multiple "unauthorized" banners #3

### ISSUE THREAD

**Issue by certrik** [certat/do-portal#32]
When the session timeouts (or cookies are deleted) and the user tries to load the user list page /#!/user_list 4 "unauthorized" banners are shown to the user. The number of banners is the number of failed requests (for the organization list it's only one)

The banners even hide the login form.

![45476712-f66d9700-b73f-11e8-970c-45d008223bc0](https://user-images.githubusercontent.com/42176839/46340302-58316a80-c635-11e8-9289-f8bb8e1013c0.png)

Proposal:

    Instead of showing the message multiple times, only show it once
    Use a more helpful error message, eg. "Session timeout. Please login again."

**Comment by davewood** [comment]
replaced the notification module.

the multiple notifications are tricky to deal with because the requests causing the errors are sent in parallel and tracking+ cancelling is not straight forward. the new module displays the errors in a way that is less obstrusive to the user.

we also got rid of the sticky notifications that didnt auto-fade-out due to a bug int he old module.

https://github.com/certat/customer-portal/commit/cf03b0accebcfb45391c1873c4b38d257b48bbe2

**Comment by certrik** [comment]
Is okay for now. Thanks.
