### ISSUE TITLE
After the session timeout menu and email address are still shown on about page

### ISSUE THREAD

**Issue by wagner-certat** [certat/do-portal#80]
* Login
* Idle until timeout
* go to (linked) about page at `/#!/about`
The menu is still and displayed and the email-address of the previous sessions' user is still shown in the logout menu link

**Comment by certrik** [comment]
Can this be related to https://github.com/certat/do-portal/issues/64 ?

**Comment by MarkHofstetter** [comment]
as discussed with eric I'll implement this "manual"

**Comment by davewood** [comment]
the about page didnt make any requests, requests were our primary way to detect if a user is still authorized or not.

with the latest commit https://github.com/certat/do-portal/commit/4a49ae07a056593db1e4cb6f99eb9ccf236653c7 this issue should be resolved because the information that is displayed on the about page will be removed.
